[target.'cfg(all(target_vendor = "pc",target_os = "windows",target_env = "msvc"))']
rustflags = ["-C", "link-arg=-s", "-C", "target-feature=+crt-static"]

[target."aarch64-unknown-linux-musl"]
linker = "aarch64-linux-musl-gcc"

[target."x86_64-unknown-linux-musl"]
linker = "x86_64-linux-musl-gcc"